class ReticleController {
  constructor(){this.canvases=Array.from(document.querySelectorAll('.reticle-canvas'));this.referenceDistanceMeters=30;this.referenceTorsoWidthMeters=.50;this.referenceTorsoHeightMeters=.72;this.horizontalFovDeg=65;this.heading=null;this.displayHeading=null;this.sensorReady=false;this.gpsReady=false;this.gpsAccuracy=null;this.gpsSpeed=null;this.gpsCourse=null}
  normalize(v){return(v%360+360)%360}
  shortestAngle(target,current){return((target-current+540)%360)-180}
  getScreenAngle(){return screen.orientation&&Number.isFinite(screen.orientation.angle)?this.normalize(screen.orientation.angle):(Number.isFinite(window.orientation)?this.normalize(window.orientation):0)}
  resizeCanvas(canvas){const r=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:r.width,h:r.height}}
  setOrientation(alpha,beta,gamma,absolute,webkitHeading=null){let newHeading=null;if(Number.isFinite(webkitHeading)){newHeading=this.normalize(webkitHeading)}else if(Number.isFinite(alpha)){newHeading=this.normalize(360-alpha+this.getScreenAngle())}if(Number.isFinite(newHeading)){this.heading=newHeading;if(this.displayHeading===null)this.displayHeading=newHeading;else this.displayHeading=this.normalize(this.displayHeading+this.shortestAngle(newHeading,this.displayHeading)*.92)}this.sensorReady=true}
  setGPS(accuracy,speed,course){this.gpsReady=true;this.gpsAccuracy=Number.isFinite(accuracy)?accuracy:null;this.gpsSpeed=Number.isFinite(speed)?speed:null;this.gpsCourse=Number.isFinite(course)?this.normalize(course):null;if(this.heading===null&&this.gpsCourse!==null&&this.gpsSpeed!==null&&this.gpsSpeed>=1.5){this.heading=this.gpsCourse;this.displayHeading=this.gpsCourse}}
  angularSizeDeg(size){return 2*Math.atan(size/(2*this.referenceDistanceMeters))*180/Math.PI}
  verticalFovDeg(w,h){const hf=this.horizontalFovDeg*Math.PI/180;return 2*Math.atan(Math.tan(hf/2)*(h/Math.max(1,w)))*180/Math.PI}
  angularToPixels(angleDeg,pixels,fovDeg){const f=fovDeg*Math.PI/180,a=angleDeg*Math.PI/180;return pixels*Math.tan(a)/(2*Math.tan(f/2))}
  draw(){this.canvases.forEach(canvas=>{const{ctx,w,h}=this.resizeCanvas(canvas),cx=w/2,cy=h/2;ctx.clearRect(0,0,w,h);ctx.save();ctx.strokeStyle='#00ff00';ctx.fillStyle='#00ff00';ctx.shadowColor='#00ff00';ctx.shadowBlur=3;ctx.lineWidth=1.5;this.drawCompass(ctx,w,h);this.drawReticle(ctx,cx,cy);this.drawTorsoReference(ctx,cx,cy,w,h);this.drawSensorInfo(ctx,w,h);ctx.restore()})}
  drawCompass(ctx,w,h){const top=4,barH=Math.min(78,Math.max(66,h*.24)),left=5,right=w-5,center=w/2,span=right-left,baseY=top+29;const heading=this.displayHeading===null?(this.heading===null?0:this.heading):this.displayHeading;const windowDeg=60;const pxPerDeg=(span-8)/(windowDeg*2);const cardinalNames={0:'N',45:'NE',90:'E',135:'SE',180:'S',225:'SO',270:'O',315:'NO'};ctx.save();ctx.fillStyle='rgba(0,0,0,.94)';ctx.strokeStyle='#00ff00';ctx.lineWidth=1.5;ctx.fillRect(left,top,span,barH);ctx.strokeRect(left,top,span,barH);ctx.beginPath();ctx.moveTo(left+3,baseY);ctx.lineTo(right-3,baseY);ctx.stroke();
    for(let d=-windowDeg;d<=windowDeg;d+=1){const x=center+d*pxPerDeg;if(x<left+2||x>right-2)continue;const deg=this.normalize(heading+d);const rounded=Math.round(deg);const isCardinal=Object.prototype.hasOwnProperty.call(cardinalNames,rounded%360);const isTen=rounded%10===0;const isFive=rounded%5===0;let tick=6;let width=1;if(isTen){tick=17;width=1.8}else if(isFive){tick=11;width=1.2}if(isCardinal){tick=24;width=2.5}ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,baseY);ctx.lineTo(x,baseY+tick);ctx.stroke();
      if(isCardinal||isTen){ctx.textAlign='center';ctx.font=isCardinal?'bold 14px monospace':'bold 9px monospace';ctx.fillText(isCardinal?cardinalNames[rounded%360]:String(rounded%360).padStart(3,'0'),x,top+55)}
    }
    ctx.strokeStyle='#00ff00';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(center,top+1);ctx.lineTo(center-9,top+13);ctx.lineTo(center+9,top+13);ctx.closePath();ctx.stroke();ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillText(this.heading===null?'BRÚJULA ESPERANDO':`RUMBO ${Math.round(this.heading).toString().padStart(3,'0')}°`,center,top+barH-5);ctx.restore()}
  drawReticle(ctx,cx,cy){ctx.save();ctx.lineWidth=1.7;ctx.beginPath();ctx.moveTo(cx-28,cy);ctx.lineTo(cx-8,cy);ctx.moveTo(cx+8,cy);ctx.lineTo(cx+28,cy);ctx.moveTo(cx,cy-28);ctx.lineTo(cx,cy-8);ctx.moveTo(cx,cy+8);ctx.lineTo(cx,cy+28);ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,3,0,Math.PI*2);ctx.stroke();ctx.restore()}
  drawTorsoReference(ctx,cx,cy,w,h){const hf=this.horizontalFovDeg*Math.PI/180;const vf=2*Math.atan(Math.tan(hf/2)*(h/Math.max(1,w)));const width=this.angularToPixels(this.angularSizeDeg(this.referenceTorsoWidthMeters),w,this.horizontalFovDeg);const height=this.angularToPixels(this.angularSizeDeg(this.referenceTorsoHeightMeters),h,vf*180/Math.PI);const x=cx-width/2,y=cy-height/2;ctx.save();ctx.lineWidth=1;ctx.setLineDash([3,3]);ctx.strokeRect(x,y,width,height);ctx.setLineDash([]);ctx.font='bold 9px monospace';ctx.textAlign='left';ctx.fillText('TORSO 30M · 0,50 × 0,72 M',x+width+5,y+10);ctx.restore()}
  drawSensorInfo(ctx,w,h){ctx.save();ctx.font='bold 9px monospace';ctx.textAlign='right';const c=this.sensorReady?'BRÚJULA OK':'BRÚJULA OFF',g=this.gpsReady?`GPS OK${this.gpsAccuracy!==null?' ±'+Math.round(this.gpsAccuracy)+'M':''}`:'GPS OFF';ctx.fillText(`${c} | ${g}`,w-7,h-7);ctx.restore()}
}